# (generated with --quick)

from typing import Any, Iterable, List, Mapping

ExtendCLass: Any

class Test(Any):
    def aaafunction1(self, list1: Mapping[int, Any], bb) -> None: ...
    def bbbfunction2(self, list1: Iterable, bb) -> None: ...

def divide(i) -> Any: ...
def returnSampleArray() -> List[int]: ...
